import { beforeEach, describe, expect, it, vi } from "vitest";

const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));

vi.mock("@tauri-apps/api/core", () => ({ invoke }));

import {
  addModIoMod,
  addModToCollection,
  addNexusMod,
  addProfileToSteam,
  applyIntroSkip,
  applyModpackProfileMetadata,
  applyOptimization,
  applyProfile,
  buildModpackFromInstalled,
  cancelNexusDownload,
  checkArchiveBlocked,
  checkForUpdate,
  checkModUpdates,
  checkNexusPremium,
  clearModBroken,
  clearModNoWorldGen,
  createCollection,
  createProfileShortcut,
  deleteCollection,
  deleteProfile,
  deleteTag,
  detectGamePath,
  detectGpuProfile,
  disableOptimization,
  downloadModArchive,
  duplicateProfile,
  ensureGameStock,
  exportModpackToFile,
  fetchModioRemoteInfo,
  fetchModpackJson,
  fetchNexusModInfo,
  fileExists,
  getAddonMap,
  getAppliedOptimizationProfile,
  getArchivePakFiles,
  getArchiveRootPath,
  getArchiveUe4ssMods,
  getAuthStatus,
  getBrokenMods,
  getCollectionColors,
  getCollectionMods,
  getCollections,
  getConfig,
  getGpuProfiles,
  getInstalledModGroups,
  getLaunchRequest,
  getModList,
  getModpackCollections,
  getModpackMeta,
  getNoWorldGenMods,
  getProfile,
  getStartupUrls,
  getSyncDetails,
  getTags,
  getUe4ssLuaConfig,
  getUe4ssModConfig,
  getUe4ssSettings,
  getWindowState,
  headlessLaunch,
  installLocalMod,
  installMods,
  installUpdate,
  isGameRunning,
  isIntroSkipApplied,
  isRunningInFlatpak,
  isScreenshotMode,
  isSteamRunning,
  isWizardScreenshotMode,
  launchGameWithGroups,
  launchVanillaGame,
  listNexusFileOptions,
  listProfiles,
  logout,
  manageWindowGeometry,
  openDir,
  openModioLogin,
  profileShortcutStatus,
  quitSteam,
  readManifestForArchive,
  refreshModMetadata,
  removeModFromCollection,
  removeProfileFromSteam,
  removeProfileShortcut,
  renameCollection,
  renameProfile,
  replaceModArchive,
  revealInFileManager,
  saveProfile,
  saveToken,
  saveWindowState,
  screenshotTheme,
  setAddonMap,
  setCollectionColor,
  setGamePath,
  setModBroken,
  setModNoWorldGen,
  setModpackMeta,
  setModpackUrl,
  setModTags,
  setSyncDetails,
  setTheme,
  setUe4ssLaunchOption,
  setUe4ssLuaConfig,
  setUe4ssModConfig,
  setUe4ssSettings,
  setWindowTitle,
  suppressExitCleanup,
  syncModLinks,
  syncModpack,
  syncModpackToRemote,
  testSyncAuth,
  toggleCollection,
  ue4ssLaunchOptionStatus,
  undoIntroSkip,
  uninstallArchive,
  uninstallMod,
  uninstallMods,
  modUsedByProfiles,
  revertUe4ssLuaConfig,
  updateConfig,
  updateModDisplayName,
  updateModSourceUrl,
  updateNexusFileId,
  validateToken,
  verifyModioApiKey,
  verifyNexusApiKey,
  type Ue4ssSettingsUpdate,
} from "../../src/lib/api/commands";
import type { ModPack, SyncAuth } from "../../src/lib/types";

/** Any wrapper exported from the commands module. */
type Wrapper = (...args: never[]) => unknown;

interface CommandCase {
  /** Wrapper under test, used to assert the table is exhaustive. */
  fn: Wrapper;
  name: string;
  /** Backend command the wrapper must forward. */
  command: string;
  /** Invocation to exercise, including default-argument paths. */
  call: () => Promise<unknown>;
  /** Expected payload; omitted for commands invoked without arguments. */
  args?: Record<string, unknown>;
}

const modpack = { name: "Pack" } as ModPack;
const autoAuth: SyncAuth = { type: "Auto" };
const passwordAuth: SyncAuth = { type: "Password", password: "secret" };
const ue4ssUpdate = {
  useObjectArrayCache: true,
  engineMajorVersion: "5",
  engineMinorVersion: "3",
  graphicsApi: "dx12",
  hookBeginPlay: true,
  consoleMode: "gui",
} as Ue4ssSettingsUpdate;

const cases: CommandCase[] = [
  {
    fn: readManifestForArchive,
    name: "readManifestForArchive",
    command: "read_manifest_for_archive",
    call: () => readManifestForArchive("mod.zip"),
    args: { archiveName: "mod.zip" },
  },
  {
    fn: downloadModArchive,
    name: "downloadModArchive without an expected hash",
    command: "download_mod_archive",
    call: () => downloadModArchive("https://dl.example/a.zip", "a.zip"),
    args: {
      url: "https://dl.example/a.zip",
      filename: "a.zip",
      expectedHash: undefined,
    },
  },
  {
    fn: downloadModArchive,
    name: "downloadModArchive with an expected hash",
    command: "download_mod_archive",
    call: () =>
      downloadModArchive("https://dl.example/b.zip", "b.zip", "abc123"),
    args: {
      url: "https://dl.example/b.zip",
      filename: "b.zip",
      expectedHash: "abc123",
    },
  },
  {
    fn: fetchModpackJson,
    name: "fetchModpackJson",
    command: "fetch_modpack_json",
    call: () => fetchModpackJson("https://pack.example/p.json"),
    args: { url: "https://pack.example/p.json" },
  },
  {
    fn: fileExists,
    name: "fileExists",
    command: "file_exists",
    call: () => fileExists("/tmp/mod.zip"),
    args: { path: "/tmp/mod.zip" },
  },
  {
    fn: getArchiveRootPath,
    name: "getArchiveRootPath",
    command: "get_archive_root_path",
    call: () => getArchiveRootPath(),
  },
  {
    fn: revealInFileManager,
    name: "revealInFileManager",
    command: "reveal_in_file_manager",
    call: () => revealInFileManager("/tmp/mod.zip"),
    args: { path: "/tmp/mod.zip" },
  },
  {
    fn: openDir,
    name: "openDir",
    command: "open_dir",
    call: () => openDir("/tmp/archives"),
    args: { path: "/tmp/archives" },
  },
  {
    fn: getConfig,
    name: "getConfig",
    command: "get_config",
    call: () => getConfig(),
  },
  {
    fn: getStartupUrls,
    name: "getStartupUrls",
    command: "get_startup_urls",
    call: () => getStartupUrls(),
  },
  {
    fn: setTheme,
    name: "setTheme",
    command: "set_theme",
    call: () => setTheme("dark"),
    args: { theme: "dark" },
  },
  {
    fn: applyIntroSkip,
    name: "applyIntroSkip",
    command: "apply_intro_skip",
    call: () => applyIntroSkip(),
  },
  {
    fn: undoIntroSkip,
    name: "undoIntroSkip",
    command: "undo_intro_skip",
    call: () => undoIntroSkip(),
  },
  {
    fn: isIntroSkipApplied,
    name: "isIntroSkipApplied",
    command: "is_intro_skip_applied",
    call: () => isIntroSkipApplied(),
  },
  {
    fn: getGpuProfiles,
    name: "getGpuProfiles",
    command: "get_gpu_profiles",
    call: () => getGpuProfiles(),
  },
  {
    fn: detectGpuProfile,
    name: "detectGpuProfile",
    command: "detect_gpu_profile",
    call: () => detectGpuProfile(),
  },
  {
    fn: applyOptimization,
    name: "applyOptimization",
    command: "apply_optimization",
    call: () => applyOptimization("balanced"),
    args: { profile: "balanced" },
  },
  {
    fn: disableOptimization,
    name: "disableOptimization",
    command: "disable_optimization",
    call: () => disableOptimization(),
  },
  {
    fn: getAppliedOptimizationProfile,
    name: "getAppliedOptimizationProfile",
    command: "get_applied_optimization_profile",
    call: () => getAppliedOptimizationProfile(),
  },
  {
    fn: detectGamePath,
    name: "detectGamePath",
    command: "detect_game_path",
    call: () => detectGamePath(),
  },
  {
    fn: setGamePath,
    name: "setGamePath",
    command: "set_game_path",
    call: () => setGamePath("/games/ron"),
    args: { path: "/games/ron" },
  },
  {
    fn: setModpackUrl,
    name: "setModpackUrl",
    command: "set_modpack_url",
    call: () => setModpackUrl("https://pack.example/p.json"),
    args: { url: "https://pack.example/p.json" },
  },
  {
    fn: syncModpack,
    name: "syncModpack",
    command: "sync_modpack",
    call: () => syncModpack(),
  },
  {
    fn: getModpackCollections,
    name: "getModpackCollections",
    command: "get_modpack_collections",
    call: () => getModpackCollections(),
  },
  {
    fn: buildModpackFromInstalled,
    name: "buildModpackFromInstalled",
    command: "build_modpack_from_installed",
    call: () => buildModpackFromInstalled(),
  },
  {
    fn: exportModpackToFile,
    name: "exportModpackToFile",
    command: "export_modpack_to_file",
    call: () => exportModpackToFile(modpack, "/tmp/out"),
    args: { modpack, dirPath: "/tmp/out" },
  },
  {
    fn: syncModpackToRemote,
    name: "syncModpackToRemote with defaults",
    command: "sync_modpack_to_remote",
    call: () => syncModpackToRemote(),
    args: { auth: { type: "Auto" }, verbose: false },
  },
  {
    fn: syncModpackToRemote,
    name: "syncModpackToRemote with explicit auth and verbose",
    command: "sync_modpack_to_remote",
    call: () => syncModpackToRemote(passwordAuth, true),
    args: { auth: passwordAuth, verbose: true },
  },
  {
    fn: testSyncAuth,
    name: "testSyncAuth",
    command: "test_sync_auth",
    call: () => testSyncAuth(autoAuth),
    args: { auth: autoAuth },
  },
  {
    fn: getCollections,
    name: "getCollections",
    command: "get_collections",
    call: () => getCollections(),
  },
  {
    fn: getCollectionMods,
    name: "getCollectionMods",
    command: "get_collection_mods",
    call: () => getCollectionMods(),
  },
  {
    fn: createCollection,
    name: "createCollection with the default mod list",
    command: "create_collection",
    call: () => createCollection("Favourites"),
    args: { name: "Favourites", modNames: [] },
  },
  {
    fn: createCollection,
    name: "createCollection with mods",
    command: "create_collection",
    call: () => createCollection("Favourites", ["Alpha"]),
    args: { name: "Favourites", modNames: ["Alpha"] },
  },
  {
    fn: addModToCollection,
    name: "addModToCollection",
    command: "add_mod_to_collection",
    call: () => addModToCollection("Favourites", "Alpha"),
    args: { collection: "Favourites", modName: "Alpha" },
  },
  {
    fn: removeModFromCollection,
    name: "removeModFromCollection",
    command: "remove_mod_from_collection",
    call: () => removeModFromCollection("Favourites", "Alpha"),
    args: { collection: "Favourites", modName: "Alpha" },
  },
  {
    fn: deleteCollection,
    name: "deleteCollection",
    command: "delete_collection",
    call: () => deleteCollection("Favourites"),
    args: { name: "Favourites" },
  },
  {
    fn: toggleCollection,
    name: "toggleCollection",
    command: "toggle_collection",
    call: () => toggleCollection("Favourites", true),
    args: { name: "Favourites", enabled: true },
  },
  {
    fn: renameCollection,
    name: "renameCollection",
    command: "rename_collection",
    call: () => renameCollection("Old", "New"),
    args: { oldName: "Old", newName: "New" },
  },
  {
    fn: getCollectionColors,
    name: "getCollectionColors",
    command: "get_collection_colors",
    call: () => getCollectionColors(),
  },
  {
    fn: setCollectionColor,
    name: "setCollectionColor with null",
    command: "set_collection_color",
    call: () => setCollectionColor("Favourites", null),
    args: { name: "Favourites", color: null },
  },
  {
    fn: setCollectionColor,
    name: "setCollectionColor with a colour",
    command: "set_collection_color",
    call: () => setCollectionColor("Favourites", "#4a90d9"),
    args: { name: "Favourites", color: "#4a90d9" },
  },
  {
    fn: getTags,
    name: "getTags",
    command: "get_tags",
    call: () => getTags(),
  },
  {
    fn: setModTags,
    name: "setModTags",
    command: "set_mod_tags",
    call: () => setModTags("Alpha", ["fun"]),
    args: { modName: "Alpha", newTags: ["fun"] },
  },
  {
    fn: deleteTag,
    name: "deleteTag",
    command: "delete_tag",
    call: () => deleteTag("fun"),
    args: { name: "fun" },
  },
  {
    fn: getBrokenMods,
    name: "getBrokenMods",
    command: "get_broken_mods",
    call: () => getBrokenMods(),
  },
  {
    fn: setModBroken,
    name: "setModBroken",
    command: "set_mod_broken",
    call: () => setModBroken("Alpha", "crashes on load"),
    args: { modName: "Alpha", note: "crashes on load" },
  },
  {
    fn: clearModBroken,
    name: "clearModBroken",
    command: "clear_mod_broken",
    call: () => clearModBroken("Alpha"),
    args: { modName: "Alpha" },
  },
  {
    fn: getNoWorldGenMods,
    name: "getNoWorldGenMods",
    command: "get_no_world_gen_mods",
    call: () => getNoWorldGenMods(),
  },
  {
    fn: setModNoWorldGen,
    name: "setModNoWorldGen",
    command: "set_mod_no_world_gen",
    call: () => setModNoWorldGen("Alpha"),
    args: { modName: "Alpha" },
  },
  {
    fn: clearModNoWorldGen,
    name: "clearModNoWorldGen",
    command: "clear_mod_no_world_gen",
    call: () => clearModNoWorldGen("Alpha"),
    args: { modName: "Alpha" },
  },
  {
    fn: getAuthStatus,
    name: "getAuthStatus",
    command: "get_auth_status",
    call: () => getAuthStatus(),
  },
  {
    fn: openModioLogin,
    name: "openModioLogin",
    command: "open_modio_login",
    call: () => openModioLogin(),
  },
  {
    fn: saveToken,
    name: "saveToken",
    command: "save_token",
    call: () => saveToken("token-value"),
    args: { token: "token-value" },
  },
  {
    fn: validateToken,
    name: "validateToken",
    command: "validate_token",
    call: () => validateToken(),
  },
  {
    fn: logout,
    name: "logout",
    command: "logout",
    call: () => logout(),
  },
  {
    fn: getModList,
    name: "getModList",
    command: "get_mod_list",
    call: () => getModList(),
  },
  {
    fn: getInstalledModGroups,
    name: "getInstalledModGroups",
    command: "get_installed_mod_groups",
    call: () => getInstalledModGroups(),
  },
  {
    fn: installMods,
    name: "installMods without collections",
    command: "install_mods",
    call: () => installMods(),
    args: { enabled_collections: undefined },
  },
  {
    fn: installMods,
    name: "installMods with collections",
    command: "install_mods",
    call: () => installMods(["Favourites"]),
    args: { enabled_collections: ["Favourites"] },
  },
  {
    fn: installLocalMod,
    name: "installLocalMod with only a file path",
    command: "install_local_mod",
    call: () => installLocalMod("/tmp/mod.zip"),
    args: {
      filePath: "/tmp/mod.zip",
      selectedPakFiles: null,
      selectedUe4ssMods: null,
      precomputedHash: null,
    },
  },
  {
    fn: installLocalMod,
    name: "installLocalMod with selections and a hash",
    command: "install_local_mod",
    call: () =>
      installLocalMod("/tmp/mod.zip", ["a.pak"], "abc123", ["Ue4ssMod"]),
    args: {
      filePath: "/tmp/mod.zip",
      selectedPakFiles: ["a.pak"],
      selectedUe4ssMods: ["Ue4ssMod"],
      precomputedHash: "abc123",
    },
  },
  {
    fn: getArchivePakFiles,
    name: "getArchivePakFiles",
    command: "get_archive_pak_files",
    call: () => getArchivePakFiles("/tmp/mod.zip"),
    args: { filePath: "/tmp/mod.zip" },
  },
  {
    fn: getArchiveUe4ssMods,
    name: "getArchiveUe4ssMods",
    command: "get_archive_ue4ss_mods",
    call: () => getArchiveUe4ssMods("/tmp/mod.zip"),
    args: { filePath: "/tmp/mod.zip" },
  },
  {
    fn: checkArchiveBlocked,
    name: "checkArchiveBlocked",
    command: "check_archive_blocked",
    call: () => checkArchiveBlocked("/tmp/mod.zip"),
    args: { filePath: "/tmp/mod.zip" },
  },
  {
    fn: addModIoMod,
    name: "addModIoMod",
    command: "add_modio_mod",
    call: () => addModIoMod("https://mod.io/g/readyornot/m/alpha"),
    args: { input: "https://mod.io/g/readyornot/m/alpha" },
  },
  {
    fn: addNexusMod,
    name: "addNexusMod with default file and browser options",
    command: "add_nexus_mod",
    call: () => addNexusMod("https://www.nexusmods.com/readyornot/mods/1234"),
    args: {
      input: "https://www.nexusmods.com/readyornot/mods/1234",
      fileId: null,
      skipOpen: null,
    },
  },
  {
    fn: addNexusMod,
    name: "addNexusMod with an explicit file id",
    command: "add_nexus_mod",
    call: () =>
      addNexusMod(
        "https://www.nexusmods.com/readyornot/mods/1234",
        26475,
        true,
      ),
    args: {
      input: "https://www.nexusmods.com/readyornot/mods/1234",
      fileId: 26475,
      skipOpen: true,
    },
  },
  {
    fn: listNexusFileOptions,
    name: "listNexusFileOptions",
    command: "list_nexus_file_options",
    call: () => listNexusFileOptions("1234"),
    args: { input: "1234" },
  },
  {
    fn: cancelNexusDownload,
    name: "cancelNexusDownload without a wait id",
    command: "cancel_nexus_download",
    call: () => cancelNexusDownload(),
    args: { waitId: null },
  },
  {
    fn: cancelNexusDownload,
    name: "cancelNexusDownload with a wait id",
    command: "cancel_nexus_download",
    call: () => cancelNexusDownload(7),
    args: { waitId: 7 },
  },
  {
    fn: checkNexusPremium,
    name: "checkNexusPremium",
    command: "check_nexus_premium",
    call: () => checkNexusPremium(),
  },
  {
    fn: updateNexusFileId,
    name: "updateNexusFileId",
    command: "update_nexus_file_id",
    call: () => updateNexusFileId("mod.zip", 26475),
    args: { archiveName: "mod.zip", fileId: 26475 },
  },
  {
    fn: fetchNexusModInfo,
    name: "fetchNexusModInfo",
    command: "fetch_nexus_mod_info",
    call: () => fetchNexusModInfo("1234"),
    args: { input: "1234" },
  },
  {
    fn: fetchModioRemoteInfo,
    name: "fetchModioRemoteInfo",
    command: "get_modio_remote_info",
    call: () => fetchModioRemoteInfo("https://mod.io/g/readyornot/m/alpha"),
    args: { input: "https://mod.io/g/readyornot/m/alpha" },
  },
  {
    fn: refreshModMetadata,
    name: "refreshModMetadata for every mod",
    command: "refresh_mod_metadata",
    call: () => refreshModMetadata(),
    args: { archiveNames: undefined },
  },
  {
    fn: refreshModMetadata,
    name: "refreshModMetadata for named archives",
    command: "refresh_mod_metadata",
    call: () => refreshModMetadata(["mod.zip"]),
    args: { archiveNames: ["mod.zip"] },
  },
  {
    fn: checkModUpdates,
    name: "checkModUpdates",
    command: "check_mod_updates",
    call: () => checkModUpdates(),
  },
  {
    fn: updateConfig,
    name: "updateConfig",
    command: "update_config",
    call: () => updateConfig({ nexus_api_key: "key", close_action: "quit" }),
    args: { updates: { nexus_api_key: "key", close_action: "quit" } },
  },
  {
    fn: verifyNexusApiKey,
    name: "verifyNexusApiKey",
    command: "verify_nexus_api_key",
    call: () => verifyNexusApiKey("nexus-key"),
    args: { apiKey: "nexus-key" },
  },
  {
    fn: verifyModioApiKey,
    name: "verifyModioApiKey",
    command: "verify_modio_api_key",
    call: () => verifyModioApiKey("modio-key"),
    args: { apiKey: "modio-key" },
  },
  {
    fn: uninstallMods,
    name: "uninstallMods",
    command: "uninstall_mods",
    call: () => uninstallMods(),
  },
  {
    fn: uninstallMod,
    name: "uninstallMod",
    command: "uninstall_mod",
    call: () => uninstallMod("a.pak"),
    args: { filename: "a.pak", removeFromAllProfiles: false },
  },
  {
    fn: uninstallMod,
    name: "uninstallMod (final)",
    command: "uninstall_mod",
    call: () => uninstallMod("a.pak", true),
    args: { filename: "a.pak", removeFromAllProfiles: true },
  },
  {
    fn: uninstallArchive,
    name: "uninstallArchive",
    command: "uninstall_archive",
    call: () => uninstallArchive("mod.zip"),
    args: { archiveName: "mod.zip", removeFromAllProfiles: false },
  },
  {
    fn: uninstallArchive,
    name: "uninstallArchive (final)",
    command: "uninstall_archive",
    call: () => uninstallArchive("mod.zip", true),
    args: { archiveName: "mod.zip", removeFromAllProfiles: true },
  },
  {
    fn: modUsedByProfiles,
    name: "modUsedByProfiles",
    command: "mod_used_by_profiles",
    call: () => modUsedByProfiles("mod.zip"),
    args: { archiveName: "mod.zip" },
  },
  {
    fn: updateModDisplayName,
    name: "updateModDisplayName",
    command: "update_mod_display_name",
    call: () => updateModDisplayName("mod.zip", "Alpha"),
    args: { archiveName: "mod.zip", displayName: "Alpha" },
  },
  {
    fn: replaceModArchive,
    name: "replaceModArchive",
    command: "replace_mod_archive",
    call: () => replaceModArchive("old.zip", "new.zip"),
    args: { oldArchiveName: "old.zip", newArchiveName: "new.zip" },
  },
  {
    fn: updateModSourceUrl,
    name: "updateModSourceUrl without a version",
    command: "update_mod_source_url",
    call: () => updateModSourceUrl("mod.zip", "https://nexusmods.com/x"),
    args: {
      archiveName: "mod.zip",
      sourceUrl: "https://nexusmods.com/x",
      version: null,
    },
  },
  {
    fn: updateModSourceUrl,
    name: "updateModSourceUrl with a version",
    command: "update_mod_source_url",
    call: () => updateModSourceUrl("mod.zip", "https://nexusmods.com/x", "1.2"),
    args: {
      archiveName: "mod.zip",
      sourceUrl: "https://nexusmods.com/x",
      version: "1.2",
    },
  },
  {
    fn: listProfiles,
    name: "listProfiles",
    command: "list_profiles",
    call: () => listProfiles(),
  },
  {
    fn: getProfile,
    name: "getProfile",
    command: "get_profile",
    call: () => getProfile("Default"),
    args: { name: "Default" },
  },
  {
    fn: saveProfile,
    name: "saveProfile",
    command: "save_profile",
    call: () => saveProfile("Default", null, ["Alpha"]),
    args: {
      name: "Default",
      description: null,
      installedModNames: ["Alpha"],
    },
  },
  {
    fn: deleteProfile,
    name: "deleteProfile",
    command: "delete_profile",
    call: () => deleteProfile("Default"),
    args: { name: "Default" },
  },
  {
    fn: renameProfile,
    name: "renameProfile",
    command: "rename_profile",
    call: () => renameProfile("Default", "Renamed", "notes", ["Alpha"]),
    args: {
      oldName: "Default",
      newName: "Renamed",
      description: "notes",
      installedModNames: ["Alpha"],
    },
  },
  {
    fn: duplicateProfile,
    name: "duplicateProfile",
    command: "duplicate_profile",
    call: () => duplicateProfile("Default", "Copy"),
    args: { oldName: "Default", newName: "Copy" },
  },
  {
    fn: applyProfile,
    name: "applyProfile",
    command: "apply_profile",
    call: () => applyProfile("Default"),
    args: { name: "Default" },
  },
  {
    fn: getModpackMeta,
    name: "getModpackMeta",
    command: "get_modpack_meta",
    call: () => getModpackMeta(),
  },
  {
    fn: setModpackMeta,
    name: "setModpackMeta with default description and author",
    command: "set_modpack_meta",
    call: () => setModpackMeta("Pack", "1.0"),
    args: { name: "Pack", version: "1.0", description: null, author: null },
  },
  {
    fn: setModpackMeta,
    name: "setModpackMeta with a description and author",
    command: "set_modpack_meta",
    call: () => setModpackMeta("Pack", "1.0", "notes", "someone"),
    args: {
      name: "Pack",
      version: "1.0",
      description: "notes",
      author: "someone",
    },
  },
  {
    fn: getSyncDetails,
    name: "getSyncDetails",
    command: "get_sync_details",
    call: () => getSyncDetails(),
  },
  {
    fn: setSyncDetails,
    name: "setSyncDetails with defaults",
    command: "set_sync_details",
    call: () => setSyncDetails(),
    args: { host: null, path: null },
  },
  {
    fn: setSyncDetails,
    name: "setSyncDetails with a host and path",
    command: "set_sync_details",
    call: () => setSyncDetails("https://host.example", "/srv/pack"),
    args: { host: "https://host.example", path: "/srv/pack" },
  },
  {
    fn: syncModLinks,
    name: "syncModLinks",
    command: "sync_mod_links",
    call: () => syncModLinks(["Alpha"]),
    args: { enabledGroups: ["Alpha"] },
  },
  {
    fn: launchGameWithGroups,
    name: "launchGameWithGroups",
    command: "launch_game_with_groups",
    call: () => launchGameWithGroups(["Alpha"]),
    args: { enabledGroups: ["Alpha"] },
  },
  {
    fn: ensureGameStock,
    name: "ensureGameStock",
    command: "ensure_game_stock",
    call: () => ensureGameStock(),
  },
  {
    fn: launchVanillaGame,
    name: "launchVanillaGame",
    command: "launch_vanilla_game",
    call: () => launchVanillaGame(),
  },
  {
    fn: isGameRunning,
    name: "isGameRunning",
    command: "is_game_running",
    call: () => isGameRunning(),
  },
  {
    fn: suppressExitCleanup,
    name: "suppressExitCleanup",
    command: "suppress_exit_cleanup",
    call: () => suppressExitCleanup(),
  },
  {
    fn: ue4ssLaunchOptionStatus,
    name: "ue4ssLaunchOptionStatus",
    command: "ue4ss_launch_option_status",
    call: () => ue4ssLaunchOptionStatus(),
  },
  {
    fn: setUe4ssLaunchOption,
    name: "setUe4ssLaunchOption",
    command: "set_ue4ss_launch_option",
    call: () => setUe4ssLaunchOption(),
  },
  {
    fn: getUe4ssSettings,
    name: "getUe4ssSettings",
    command: "get_ue4ss_settings",
    call: () => getUe4ssSettings(),
  },
  {
    fn: setUe4ssSettings,
    name: "setUe4ssSettings",
    command: "set_ue4ss_settings",
    call: () => setUe4ssSettings(ue4ssUpdate),
    args: { updates: ue4ssUpdate },
  },
  {
    fn: getUe4ssModConfig,
    name: "getUe4ssModConfig",
    command: "get_ue4ss_mod_config",
    call: () => getUe4ssModConfig("SRankAlert"),
    args: { modName: "SRankAlert" },
  },
  {
    fn: setUe4ssModConfig,
    name: "setUe4ssModConfig",
    command: "set_ue4ss_mod_config",
    call: () => setUe4ssModConfig("SRankAlert", "{}"),
    args: { modName: "SRankAlert", content: "{}" },
  },
  {
    fn: getUe4ssLuaConfig,
    name: "getUe4ssLuaConfig",
    command: "get_ue4ss_lua_config",
    call: () => getUe4ssLuaConfig("RoundReport"),
    args: { modName: "RoundReport" },
  },
  {
    fn: setUe4ssLuaConfig,
    name: "setUe4ssLuaConfig",
    command: "set_ue4ss_lua_config",
    call: () => setUe4ssLuaConfig("RoundReport", "return { watch_ms = 500 }"),
    args: {
      modName: "RoundReport",
      content: "return { watch_ms = 500 }",
    },
  },
  {
    fn: revertUe4ssLuaConfig,
    name: "revertUe4ssLuaConfig",
    command: "revert_ue4ss_lua_config",
    call: () => revertUe4ssLuaConfig("RoundReport"),
    args: { modName: "RoundReport" },
  },
  {
    fn: setWindowTitle,
    name: "setWindowTitle",
    command: "set_window_title",
    call: () => setWindowTitle("RoN Mod Manager"),
    args: { title: "RoN Mod Manager" },
  },
  {
    fn: saveWindowState,
    name: "saveWindowState without geometry",
    command: "save_window_state",
    call: () => saveWindowState(),
    args: { width: undefined, height: undefined, x: undefined, y: undefined },
  },
  {
    fn: saveWindowState,
    name: "saveWindowState with geometry",
    command: "save_window_state",
    call: () => saveWindowState(1280, 720, 10, 20),
    args: { width: 1280, height: 720, x: 10, y: 20 },
  },
  {
    fn: getWindowState,
    name: "getWindowState",
    command: "get_window_state",
    call: () => getWindowState(),
  },
  {
    fn: manageWindowGeometry,
    name: "manageWindowGeometry",
    command: "manage_window_geometry",
    call: () => manageWindowGeometry(),
  },
  {
    fn: isScreenshotMode,
    name: "isScreenshotMode",
    command: "is_screenshot_mode",
    call: () => isScreenshotMode(),
  },
  {
    fn: isWizardScreenshotMode,
    name: "isWizardScreenshotMode",
    command: "is_wizard_screenshot_mode",
    call: () => isWizardScreenshotMode(),
  },
  {
    fn: screenshotTheme,
    name: "screenshotTheme",
    command: "screenshot_theme",
    call: () => screenshotTheme(),
  },
  {
    fn: checkForUpdate,
    name: "checkForUpdate",
    command: "check_for_update",
    call: () => checkForUpdate(),
  },
  {
    fn: installUpdate,
    name: "installUpdate",
    command: "install_update",
    call: () => installUpdate(),
  },
  {
    fn: isRunningInFlatpak,
    name: "isRunningInFlatpak",
    command: "is_flatpak",
    call: () => isRunningInFlatpak(),
  },
  {
    fn: getAddonMap,
    name: "getAddonMap",
    command: "get_addon_map",
    call: () => getAddonMap(),
  },
  {
    fn: setAddonMap,
    name: "setAddonMap",
    command: "set_addon_map",
    call: () => setAddonMap({ Alpha: ["Beta"] }),
    args: { map: { Alpha: ["Beta"] } },
  },
  {
    fn: applyModpackProfileMetadata,
    name: "applyModpackProfileMetadata",
    command: "apply_modpack_profile_metadata",
    call: () => applyModpackProfileMetadata(modpack),
    args: { modpack },
  },
  {
    fn: getLaunchRequest,
    name: "getLaunchRequest",
    command: "get_launch_request",
    call: () => getLaunchRequest(),
  },
  {
    fn: headlessLaunch,
    name: "headlessLaunch with defaults",
    command: "headless_launch",
    call: () => headlessLaunch(),
    args: { profile: null, vanilla: false },
  },
  {
    fn: headlessLaunch,
    name: "headlessLaunch with a profile and vanilla mode",
    command: "headless_launch",
    call: () => headlessLaunch("Default", true),
    args: { profile: "Default", vanilla: true },
  },
  {
    fn: createProfileShortcut,
    name: "createProfileShortcut with defaults",
    command: "create_profile_shortcut",
    call: () => createProfileShortcut("Default"),
    args: { profile: "Default", vanilla: false, desktopCopy: false },
  },
  {
    fn: createProfileShortcut,
    name: "createProfileShortcut with a desktop copy",
    command: "create_profile_shortcut",
    call: () => createProfileShortcut("Default", true, true),
    args: { profile: "Default", vanilla: true, desktopCopy: true },
  },
  {
    fn: removeProfileShortcut,
    name: "removeProfileShortcut",
    command: "remove_profile_shortcut",
    call: () => removeProfileShortcut("Default"),
    args: { profile: "Default" },
  },
  {
    fn: addProfileToSteam,
    name: "addProfileToSteam with the default vanilla flag",
    command: "add_profile_to_steam",
    call: () => addProfileToSteam("Default"),
    args: { profile: "Default", vanilla: false },
  },
  {
    fn: addProfileToSteam,
    name: "addProfileToSteam with vanilla mode",
    command: "add_profile_to_steam",
    call: () => addProfileToSteam("Default", true),
    args: { profile: "Default", vanilla: true },
  },
  {
    fn: removeProfileFromSteam,
    name: "removeProfileFromSteam",
    command: "remove_profile_from_steam",
    call: () => removeProfileFromSteam("Default"),
    args: { profile: "Default" },
  },
  {
    fn: profileShortcutStatus,
    name: "profileShortcutStatus",
    command: "profile_shortcut_status",
    call: () => profileShortcutStatus("Default"),
    args: { profile: "Default" },
  },
  {
    fn: isSteamRunning,
    name: "isSteamRunning",
    command: "steam_running",
    call: () => isSteamRunning(),
  },
  {
    fn: quitSteam,
    name: "quitSteam",
    command: "quit_steam",
    call: () => quitSteam(),
  },
];

beforeEach(() => {
  invoke.mockReset();
  invoke.mockResolvedValue(undefined);
});

describe("command wrappers", () => {
  it.each(cases)("$name forwards $command", async ({ command, call, args }) => {
    await call();
    if (args === undefined) {
      expect(invoke).toHaveBeenCalledWith(command);
    } else {
      expect(invoke).toHaveBeenCalledWith(command, args);
    }
    expect(invoke).toHaveBeenCalledTimes(1);
  });

  it("has a case for every exported wrapper", async () => {
    const module = await import("../../src/lib/api/commands");
    const covered = new Set<Wrapper>(cases.map((c) => c.fn));
    const uncovered = Object.entries(module)
      .filter(([, value]) => typeof value === "function")
      .map(([name]) => name)
      .filter(
        (name) => !covered.has(module[name as keyof typeof module] as Wrapper),
      );
    expect(uncovered).toEqual([]);
  });
});
