name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable
      - run: pnpm install --frozen-lockfile
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: pnpm tauri
      - uses: actions/upload-artifact@v4
        with:
          name: ronmodmanager-${{ matrix.os }}
          path: src-tauri/target/release/bundle
